---
title: "sentimentAna"
output: html_document
---

## 감정 분석 (영화 댓글)

### 01 라이브러리 준비 
```{r}
rm(list=ls())
library(wordcloud)
library(KoNLP)
```

### 02 사전 불러오기 
```{r}
useSejongDic()
fname = "D:/data/30_AgainCourt.txt"
road1 = readLines(fname)
```

### 03 단어 사전 준비 
```{r}
### 긍정단어 부정단어
pos.words = scan("D:/data/pos_kor_words.txt", what='character', comment.char=";")
neg.words = scan("D:/data/neg_kor_words.txt", what='character', comment.char=";")

```

### 04 텍스트 전처리  
```{r}
sentence <- road1
require(plyr)
# 구두점 문자, ! " # $ % & ’ ( ) * + , - . / : ; < = > ? @ [  ] ^ _ ` { | } ~. 제거
sentence <- gsub('[[:punct:]]', "", sentence)
# \n, \r 같은 제어문자 등 제거
sentence <- gsub('[[:cntrl:]]', "", sentence)
# 숫자 제거 
sentence <- gsub('\\d+', "", sentence)
head(sentence)
```


### 04 텍스트 전처리  
```{r}
# USE.NAMES 행 이름 없이
wordlist <-sapply(sentence, extractNoun, USE.NAMES=F)
words <- unlist(wordlist)   # 단어를 하나의 벡터로 
head(words)

length(words)      # 약 7062여개
```

### 05 점수 확인   
```{r}
## 감성 분석을위한 점수 확인
pos.matches <- match(words, pos.words)
neg.matches <- match(words, neg.words)

pos.match <- !is.na(pos.matches)
sum(pos.match)

neg.match <- !is.na(neg.matches)
sum(neg.match)

# 점수 확인
score <- sum(pos.match) - sum(neg.match)
score

```

### 06 점수 확인 
```{r}
pos_word <- words[pos.match ]
neg_word <- words[neg.match ]

pos_cnt <- table(pos_word)
pos_cnt; 
neg_cnt <- table(neg_word)

pos_cnt_sort <- sort(pos_cnt, decreasing = T)
neg_cnt_sort <- sort(neg_cnt, decreasing = T)

## TOP 5 단어 그래프 보기
barplot(pos_cnt_sort[5:0], main='긍정 단어 TOP 5', horiz=T, col=c("green", "blue", "yellow"))

```

### 06 점수 확인 
```{r}
library(wordcloud2)
library(RColorBrewer)
palette = brewer.pal(8, "Set2")

base_word2 <- as.data.frame(pos_cnt, stringsAsFactors = F)
wordcloud2(data=base_word2, fontFamily = '나눔바른고딕')

```

